# Generated by Django 2.2.5 on 2020-01-02 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chatting',
        ),
    ]
