# Generated by Django 2.2.5 on 2020-01-03 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0002_auto_20200104_0040'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
