# Generated by Django 2.2.5 on 2020-01-02 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0003_chatting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chatting',
        ),
    ]
