# Generated by Django 2.2.5 on 2020-01-02 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatting', '0004_delete_chatting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('message', models.TextField(verbose_name='message')),
                ('description', models.TextField(verbose_name='description')),
                ('type', models.IntegerField(choices=[(1, 'Sedan'), (2, 'Truck'), (3, 'SUV')], verbose_name='type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Chatting',
                'verbose_name_plural': 'Chattings',
            },
        ),
    ]
