# Generated by Django 2.2.5 on 2020-01-03 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0004_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
